### ISSUE TITLE
LTS

### ISSUE THREAD

**Issue by Alex-Wenner-FHR** [MideTechnology/ebmlite#125]
Is this still supported? Just curious about LTS of this framework!

**Comment by StokesMIDE** [comment]
We don't have an official LTS strategy, but LTS versions seem somewhat uncommon for Python packages. However, `ebmlite` is a critical component of several projects here at Mide Technology, both internal and external. As such, we're committed to developing and maintaining it indefinitely. If/when we ever introduce API-breaking changes (v 4.0+), we will probably end up with something like an LTR branch of v 3.x, but that's not currently in the plans.

**Comment by Alex-Wenner-FHR** [comment]
Great! That is what I wanted to be sure of nonetheless. Thank you kindly
