### ISSUE TITLE
Threaded_file fails to import in python 3

### ISSUE THREAD

**Issue by CFlaniganMide** [MideTechnology/ebmlite#59]
> 
> 
> This currently fails on my machine due to some errors in threaded_file.py. Specifically, if I try to import it manually in a console, I get this traceback:
> 
> ```
> >>> import ebmlite.threaded_file
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/crepegoat/repos/ebmlite/ebmlite/threaded_file.py", line 19, in <module>
>     class ThreadAwareFile(file):
> NameError: name 'file' is not defined
> ```
> 
> Not sure which of the following should happen:
> 
>     * can it be fixed easily?
> 
>     * just remove the file? (it errors if you even try to import it; I don't know what its purpose is, but it's clearly not being used.)
> 
>     * just suppress the error?

It looks like `file` was removed in python 3, and the correct change is to replace references to `file` with `io.IOBase`

https://portingguide.readthedocs.io/en/latest/builtins.html#removed-file

_Originally posted by @CFlaniganMide in https://github.com/MideTechnology/ebmlite/issues/58#issuecomment-805839635_

**Comment by CrepeGoat** [comment]
just merged in #58 with a change to threaded_file.py to remove the uses of `file`. HOWEVER I still have no idea if that actually fixed the code, or if the code has any other issues or not.

I think as far as answering "what do we do with threaded_file.py?" this issue is still relevant.

**Comment by StokesMIDE** [comment]
That *should* fix things. `ThreadAwareFile` was only subclassed from `file` for the sake of anyone using `isinstance()` on it, in case that just quacking like a `file` wasn't enough.

**Comment by StokesMIDE** [comment]
> * just remove the file? (it errors if you even try to import it; I don't know what its purpose is, but it's clearly not being used.)

Its purpose is to provide an optional means of making `ebmlite` thread safe. During random access, `ebmlite` does many seeks, so a 'real' file would cause threads to conflict. I think it's useful, but it needs to be documented. The `ebmlite` package as a whole needs more documentation, so it could be written up if/when that happens.

In any case, I believe the specific issue has been solved.
