### ISSUE TITLE
Revise the IDE parsing example

### ISSUE THREAD

**Issue by StokesMIDE** [MideTechnology/ebmlite#6]
The current IDE parsing example loads the entire file into memory, which will only work for small files. Since this is the example, I think users will assume that this is the recommended way to read IDE files. A better example would be to iterate the elements in the file.

Assigning to @CFlaniganMide, but if you don't have time, I can create a new IDE example.

**Comment by CFlaniganMide** [comment]
37eb5ee0826abc9193fb21f108bb219dedad4733 fixes this, data is now only fully loaded right before it's used.
