### ISSUE TITLE
Documentation clarification and expansion

### ISSUE THREAD

**Issue by jsa5593** [MideTechnology/ebmlite#62]
Example command line usage syntax is different in the README.md and when a command is put in wrong.
README.md: util.py {xml2ebml|ebml2xml|view} {FILE1.ebml|FILE1.xml} SCHEMA.xml [-o {FILE2.xml|FILE2.ebml}] [-c|--clobber] [-p|--pretty]
Command Line: util.py [-h] [-o [FILE.xml|FILE.ebml]] [-c] [-p] {xml2ebml,ebml2xml,view} [FILE.ebml|FILE.xml] SCHEMA.xml

Also put in example command line usage to show correct syntax for usage. For instance 'python ebmlite/util.py ebml2xml ~/Documents/DAQ/DAQ00001_000047.IDE' this is wrong but explanation of how to do it right is confusing.

**Comment by pscheidler** [comment]
This was addressed a while ago
