### ISSUE TITLE
remove test folder from pip installation

### ISSUE THREAD

**Issue by CrepeGoat** [MideTechnology/ebmlite#67]
running `pip install ebmlite` adds two folders to the interpreter's site-packages:
- "ebmlite" (and the corresponding ".egg-info") -> this is correct and expected
- "tests" -> this is unnecessary

this is anecdotally shown in the screencap from my machine copied below:
![Screen Shot 2021-04-15 at 10 15 33](https://user-images.githubusercontent.com/5862803/114885674-e117e800-9dd4-11eb-9b4c-67eb2defa235.png)

I think **this folder should be removed**; I'm confident no users need access to this folder and it takes up extra space, and potentially this could have naming conflicts with another library's folders that results in installation errors.

**Comment by StokesMIDE** [comment]
I believe this was resolved in PR #68.
